services:
  db:
    image: postgres
    container_name: fitness_postgres
    restart: always
    environment:
      POSTGRES_DB: fitness_db
      POSTGRES_USER: fitness_user
      POSTGRES_PASSWORD: fitness_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  web:
    build: .
    container_name: fitness_web
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - uwsgi_socket:/var/run/app-uwsgi
    depends_on:
      - db

  nginx:
    build: ./nginx/
    restart: always  
    ports:
      - "8888:80"
    volumes:
      - uwsgi_socket:/var/run/app-uwsgi
      - ./nginx/mysite.nginx.conf:/etc/nginx/sites-enabled/mysite.nginx.conf
    depends_on: 
      - web

volumes:
  postgres_data:
  uwsgi_socket:
